include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat these as errors in CI so we don't ship with them.
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    sort_child_properties_last: true
